# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e700eb7247272080addea4fdefe4e597e214ec7e119a132b0aef33783f00a5a07e9202535ef84a8f019167673f6d09e802afd2dff2af3ca6577fea217e9652eb

test:
  secret_key_base: 651b060fc00b70043a6ecc5687c2bf9a11dba1c4abb5efdeeb61e5ea669d0adc17fbc2a76d3dd5b6963eec25b22aadb8694c5b937d5c534e9b937ad69d6e9118

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
